{
  "name": "music-room",
  "main": "src/index.js",
  "compatibility_date": "2026-08-19",

  "durable_objects": {
    "bindings": [
      {
        "name": "ROOMS",
        "class_name": "Room"
      }
    ]
  },

  "migrations": [
    {
      "tag": "v1",
      "new_sqlite_classes": ["Room"]
    }
  ],

  "assets": {
    "directory": "./public"
  }
}
